### PR TITLE
Fix NullPointerException in JvmStats on some platforms

### PR DESCRIPTION
**Pull request by olix0r**
Problem

According to documentation, two ManagementFactory calls may return null on some
platforms.  TwitterServer's JvmStats do not handle this case well, which
results in NullPointerExceptions during startup.

Solution

Handle the null case explicitly.

### CODE REVIEW

**Comment by mosesn** [comment]
LGTM

**Comment by olix0r** [comment]
null return values documented at https://docs.oracle.com/javase/7/docs/api/?java/lang/management/ManagementFactory.html

**Comment by mosesn** [comment]
Thanks for the contribution, we've merged this internally!

**Comment by mosesn** [comment]
Boomshakalaka!  https://github.com/twitter/twitter-server/commit/d5e9d090d68d96ab128c3d55cc60f7417345e344

**Pull request closed without merging**
